import React, { useState, useEffect } from 'react';
import { api } from '../services/api';
import { 
  Sparkles, BookOpen, AlertTriangle, Users, Lightbulb, 
  Award, ArrowLeft, CheckCircle2, TrendingUp, Download, Share2
} from 'lucide-react';

export const PostClassSummary = ({ sessionId = 1, setActiveTab }) => {
  const [summary, setSummary] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchSummary = async () => {
      try {
        const data = await api.getSummary(sessionId || 1);
        setSummary(data);
      } catch (err) {
        console.error('Failed to fetch summary:', err);
      } finally {
        setLoading(false);
      }
    };
    fetchSummary();
  }, [sessionId]);

  if (loading) {
    return (
      <div className="min-h-[70vh] flex flex-col items-center justify-center space-y-3 text-slate-400">
        <Sparkles className="w-8 h-8 text-cyan-400 animate-spin" />
        <p className="text-xs font-semibold">Generating Post-Class Intelligence with Classora AI...</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen py-8 px-4 lg:px-8 max-w-5xl mx-auto space-y-8 animate-in fade-in">
      
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-4 pb-4 border-b border-slate-800">
        <div className="flex items-center space-x-3">
          <button
            onClick={() => setActiveTab('classroom')}
            className="p-2 rounded-xl glass-card hover:border-cyan-500/40 text-slate-400 hover:text-white transition-all"
          >
            <ArrowLeft className="w-4 h-4" />
          </button>
          <div>
            <div className="flex items-center space-x-2">
              <h1 className="text-2xl font-extrabold text-slate-100">
                Post-Class Intelligence Summary
              </h1>
              <span className="text-xs font-bold px-2.5 py-0.5 rounded-full bg-cyan-500/20 text-cyan-300 border border-cyan-500/30">
                AI Generated
              </span>
            </div>
            <p className="text-xs text-slate-400 mt-0.5">
              Comprehensive analytics & pedagogical recommendations generated by Classora AI.
            </p>
          </div>
        </div>

        <div className="flex items-center space-x-2">
          <button
            onClick={() => alert("Summary report exported successfully as PDF/JSON!")}
            className="px-3.5 py-2 rounded-xl glass-card border border-slate-700 hover:border-cyan-400 text-xs font-bold text-slate-200 hover:text-white transition-all flex items-center space-x-1.5"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Export Report</span>
          </button>
          <button
            onClick={() => setActiveTab('teacher_dash')}
            className="px-4 py-2 rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 text-white text-xs font-bold hover:shadow-lg hover:shadow-cyan-500/25 transition-all"
          >
            Back to Dashboard
          </button>
        </div>
      </div>

      {/* Metrics Overview Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="p-5 rounded-2xl glass-card border-t-2 border-t-cyan-500 space-y-1">
          <span className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">Topics Mastered</span>
          <div className="text-2xl font-extrabold text-slate-100">{summary?.topics_covered?.length || 4}</div>
          <p className="text-[11px] text-cyan-400">Quadratic Equations & Roots</p>
        </div>

        <div className="p-5 rounded-2xl glass-card border-t-2 border-t-blue-500 space-y-1">
          <span className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">Spoken Questions</span>
          <div className="text-2xl font-extrabold text-slate-100">{summary?.total_questions || 17}</div>
          <p className="text-[11px] text-blue-400">Voice interactions logged</p>
        </div>

        <div className="p-5 rounded-2xl glass-card border-t-2 border-t-amber-500 space-y-1">
          <span className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">Students Needing Support</span>
          <div className="text-2xl font-extrabold text-amber-400">{summary?.students_needing_support || 3}</div>
          <p className="text-[11px] text-slate-400">Identified by gap clustering</p>
        </div>

        <div className="p-5 rounded-2xl glass-card border-t-2 border-t-emerald-500 space-y-1">
          <span className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">Class Engagement Score</span>
          <div className="text-2xl font-extrabold text-emerald-400">{summary?.overall_engagement_score || 88.5}%</div>
          <p className="text-[11px] text-emerald-400">Active turn participation</p>
        </div>
      </div>

      {/* Recommended Pedagogical Intervention */}
      <div className="p-6 rounded-2xl glass-panel border-l-4 border-l-amber-500 bg-amber-950/15 shadow-xl space-y-3">
        <div className="flex items-center space-x-2">
          <Lightbulb className="w-5 h-5 text-amber-400" />
          <h3 className="text-sm font-extrabold uppercase tracking-wider text-amber-300">
            Recommended Action for Next Class:
          </h3>
        </div>
        <p className="text-sm text-slate-200 leading-relaxed font-medium">
          "{summary?.recommended_action || 'Conduct a 10-minute recap on middle-term splitting rules with negative signs before moving on to the Quadratic Formula.'}"
        </p>
      </div>

      {/* Common Learning Gaps */}
      <div className="p-6 rounded-2xl glass-panel border border-slate-800/80 shadow-xl space-y-4">
        <div className="flex items-center space-x-2">
          <AlertTriangle className="w-5 h-5 text-rose-400" />
          <h3 className="text-sm font-extrabold uppercase tracking-wider text-slate-100">
            Common Conceptual Learning Gaps Identified:
          </h3>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {(summary?.common_learning_gaps || [
            "Factorization & Middle Term Splitting",
            "Negative Roots & Discriminant Signs"
          ]).map((gap, idx) => (
            <div key={idx} className="p-3.5 rounded-xl glass-card border border-rose-500/20 bg-rose-950/10 flex items-start space-x-2.5">
              <div className="w-6 h-6 rounded-lg bg-rose-500/20 text-rose-400 font-bold text-xs flex items-center justify-center shrink-0 mt-0.5">
                {idx + 1}
              </div>
              <div>
                <h4 className="text-xs font-bold text-slate-200">{gap}</h4>
                <p className="text-[11px] text-slate-400 mt-0.5">
                  Semantic difficulty detected during live verbal turns.
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Individual Student Learning Profiles */}
      <div className="p-6 rounded-2xl glass-panel border border-slate-800/80 shadow-xl space-y-4">
        <div className="flex items-center space-x-2">
          <Users className="w-5 h-5 text-cyan-400" />
          <h3 className="text-sm font-extrabold uppercase tracking-wider text-slate-100">
            Personalized Student Progress Cards:
          </h3>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {summary?.student_insights && Object.entries(summary.student_insights).map(([name, note], idx) => (
            <div key={idx} className="p-4 rounded-xl glass-card space-y-2">
              <div className="flex items-center justify-between">
                <h4 className="text-xs font-bold text-slate-100">{name}</h4>
                <span className="text-[10px] px-2 py-0.5 rounded bg-slate-800 text-cyan-300 font-mono">
                  {name.includes('Rahul') ? 'Beginner' : name.includes('Priya') ? 'Advanced' : 'Intermediate'}
                </span>
              </div>
              <p className="text-[11px] text-slate-300 leading-relaxed">
                {note}
              </p>
            </div>
          ))}
        </div>
      </div>

    </div>
  );
};
